# Generated by Django 4.1.13 on 2024-08-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='condition',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='drugname',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
